### ISSUE TITLE
Error when saving new model

### ISSUE THREAD

**Issue by jstutz93** [wrightd/build4thewin#3]
When trying to upload a new model with the data filled out in the screenshot below, I received an invalid input error. Not sure if I missed a required field or if something else was going on. 

<img width="937" alt="Model Submission Error" src="https://user-images.githubusercontent.com/20134117/221383649-df5ea0a6-a380-4829-b556-afa5134e2e0c.png">

**Comment by wrightd** [comment]
Thanks for the report - looks like one of the updates I made yesterday broke creating new models that didn't have a picture. It's fixed now - you will need to reload the site (F5) but then should be able to create a model (with or without a picture!).
